language: java
jdk: oraclejdk7

before_install:
  # Install base Android SDK
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

before_script:

script: mvn clean install