language: java
jdk: oraclejdk7

-export ANDROID_HOME='pwd'/android-sdk-linux

install: mvn install -Dmaven.compiler.target=1.5 -Dmaven.compiler.source=1.5 -DskipTests=false -Dandroid.sdk.path='pwd'/android-sk-linux -B
script: mvn test -Dmaven.compiler.target=1.5 -Dmaven.compiler.source=1.5 -B

